### ISSUE TITLE
Paring opportunities

### ISSUE THREAD

**Issue by PaulClark2** [18F/fec-transition#113]
- [ ] Pattern library https://github.com/18F/fec-transition/issues/70
     Dorothy
     Jim
    Lauren
    Jun
    Cristl

- [ ] Debuging and monitoring https://github.com/18F/fec-transition/issues/82
    Priya
    Rohan
    Jun
    Helen
    Cristl

- [ ] Ticket workflow - work a ticket from start to finish https://github.com/18F/fec-transition/issues/87
    Priya
    Rohan
    Jun
    Helen
    Jean
    Cristl

- [ ] API refactor - downloads https://github.com/18F/fec-transition/issues/108
    Priya
    Rohan
    Jun

- [ ] API filters https://github.com/18F/fec-transition/issues/109
    Priya
    Rohan
    Jun
    Helen
    Cristl

- [ ] Adding indexes to materialized views https://github.com/18F/fec-transition/issues/112
    Priya
    Rohan
    Helen
    Jun
    Jean

- [ ] Cloudwatch https://github.com/18F/fec-cms/issues/1168
    Rohan
    Jun
    Priya
