### ISSUE TITLE
Training opportunities 

### ISSUE THREAD

**Issue by PaulClark2** [18F/fec-transition#114]
- [X] GitFlow workshop https://github.com/18F/fec-transition/issues/64

- [X] Research repository and UX training https://github.com/18F/fec-transition/issues/67

- [X] Mac setup https://github.com/18F/fec-transition/issues/69

- [X] Elastic search https://github.com/18F/fec-transition/issues/75

- [ ] Infrastructure training https://github.com/18F/fec-transition/issues/77
    Rohan
    Jun
    Helen
    Cristl

- [ ] Postgres training https://github.com/18F/fec-transition/issues/102
    Rohan
    Jun
    Helen
    Jean
    Cristl

- [ ] Log training -- Kibana, cf logs, etc.https://github.com/18F/fec-transition/issues/84
    Priya
    Rohan
    Helen
    Jun
    Cristl
    Pat

- [ ] New Relic https://github.com/18F/fec-cms/issues/1169
    Priya
    Rohan
    Helen
    Jun
    Jean
    Cristl

- [ ] Run and edit pattern libary locally https://github.com/18F/fec-style/issues/735
    Dorothy
    Jim
    Lauren 
    Jun
    Cristl

- [ ] API training for data users https://github.com/18F/fec-transition/issues/115
     Press
     Public Records
     RAD
     Jeff
     Paul

- [ ] Overview of Sequel Alchemy https://github.com/18F/fec-transition/issues/116
